### ISSUE TITLE
external resources issue

### ISSUE THREAD

**Issue by Adamlixi** [discord/embedded-app-sdk#276]
Hi Discord! I meet problems when request external resources.

I am building a game activities using embedded-app-sdk.

tech: Nodejs + Threejs + third party sdk.

Code:
![image](https://github.com/user-attachments/assets/3a310d76-db54-42c6-b038-ffd802ecfb08)

Problem:
![image](https://github.com/user-attachments/assets/4e82fab1-09b4-44b1-9905-f1680af41bac)

I try to solve the problem using patchUrlMappings:
![image](https://github.com/user-attachments/assets/b142be79-010f-4e08-8a78-ddba7bff1692)
and change the url.
![image](https://github.com/user-attachments/assets/5054b770-1c79-411e-aaca-144761a759b9)
But still get error:
![image](https://github.com/user-attachments/assets/308633e7-fd33-4b8f-bf02-c3b1838ce8e6)

**Comment by elainemckinley** [comment]
Hi!
Here's the docs around patchUrlMappings if you haven't seen them: https://discord.com/developers/docs/activities/development-guides#using-external-resources

Basically, if you have control over the URL yourself (as you do) you'll want to just use the URL you [set up in mappings](https://discord.com/developers/docs/activities/development-guides#url-mapping) directly. You won't even have to use `patchUrlMappings` since you can address the proxy directly instead.

`patchUrlMappings` only exists in case you didn't have the code to address the proxied URL yourself (i.e. if it came from a third-party library).

Feel free to reopen in case this doesn't answer the question. Thanks!
